In [8]:
import pandas as pd
df = pd.read_csv('ANOVA.csv')
df

    index treatment  value
0       0         A     25
1       1         A     30
2       2         A     28
3       3         A     36
4       4         A     29
5       0         B     45
6       1         B     55
7       2         B     29
8       3         B     56
9       4         B     40
10      0         C     30
11      1         C     29
12      2         C     33
13      3         C     37
14      4         C     27
15      0         D     54
16      1         D     60
17      2         D     51
18      3         D     62
19      4         D     73

In [9]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

model = ols('value ~ C(treatment)', data=df).fit()
anova_table = sm.stats.anova_lm(model,typ=2)
anova_table

               sum_sq    df         F    PR(>F)
C(treatment)  3010.95   3.0  17.49281  0.000026
Residual       918.00  16.0       NaN       NaN

In [17]:
from bioinfokit.analys import stat
res = stat()
res.anova_stat(data=df, res_var='value', anova_model='value ~ C(treatments)')
res.anova_summary

AttributeError: 'stat' object has no attribute 'anova_stat'

In [ ]:
from bioinfokit.analys import stat
res =stat()
res.tukey_hsd(df, res_var='value',xfac_var='tratments', anova_model='value ~ C(treatment)')
res.tukey_summary

AttributeError: 'stat' object has no attribute 'tukey_hsd'

In [ ]:
from bioinfokit.analys import stat